apiVersion: v1
kind: Secret
metadata:
  name: db-secret

type: Opaque

data:
  username: YWRtaW4xMjM=
  password: YWRtaW4xMjM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  volumes:
    - name: db-volume
      secret:
      secretName: db-secret
  containers:
  - volumeMounts:
    - name: db-volume
      mountPath: "/etc/secrets"
  name: mysql
  PORT: 80    


---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret

type: Opaque

data:
  username: YWRtaW4xMjM=
  password: YWRtaW4xMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        ap: nginx
    spec:
      volumes:
      - name: db_volume
        secret:
          - secretName: db-secret
      containers:
      - name: mysql
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:

        volumeMounts:
        - name: db_volume
          mountPath: /etc/secrets