apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
  - ReadWriteOnce

  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc

spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx

        volumeMounts:
        - name: my-storage
          mountPath: /usr/share/nginx/html

      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: my-pvc