apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-svc
  template:
    metadata:
      labels:
        app: mongo
        version: v1.0
    spec:
      containers:
        - name: db
          image: mongo:5.0.24
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce